# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_owner_id', models.CharField(max_length=255)),
                ('channel_create_date', models.DateTimeField()),
                ('record_create_date', models.DateTimeField()),
                ('record_last_modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('playlist_channel_id', models.CharField(max_length=255)),
                ('playlist_name', models.CharField(max_length=255)),
                ('playlist_owner_id', models.CharField(max_length=255)),
                ('playlist_create_date', models.DateTimeField()),
                ('record_create_date', models.DateTimeField()),
                ('record_last_modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistVideos',
            fields=[
                ('playlist_video_key', models.CharField(max_length=510, primary_key=True, serialize=False)),
                ('has_been_posted', models.IntegerField(default=0)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_create_date', models.DateTimeField()),
                ('record_create_date', models.DateTimeField()),
                ('record_last_modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=255)),
                ('video_owner_id', models.CharField(max_length=255)),
                ('video_name', models.CharField(max_length=255)),
                ('video_published_date', models.DateTimeField()),
                ('record_created_date', models.DateTimeField()),
                ('record_last_modified_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='playlistvideos',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.Video'),
        ),
    ]
