# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0002_auto_20161204_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goouser',
            options={'verbose_name': 'Google User'},
        ),
    ]
