# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0003_auto_20161204_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('playlist_video_key', models.CharField(max_length=510, primary_key=True, serialize=False)),
                ('has_been_posted', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='GooUser',
        ),
        migrations.RemoveField(
            model_name='playlistvideos',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='playlistvideos',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='channel_owner_id',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_owner_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_owner_id',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.Channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.Channel'),
        ),
        migrations.DeleteModel(
            name='PlaylistVideos',
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.Playlist'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.Video'),
        ),
    ]
